// ==========================================
// キャラクターデータ
// 新キャラはこの CHARS に追加してください。
// commands の合計は 8 枚にしてください。
// ==========================================
const CHARS = {
  tsukune:{
    id:'tsukune',
    name:'騎兵隊長・ツクネ',
    role:'英雄',
    race:'騎士♀',
    rarity:2,
    power:1020,
    charisma:400,
    intel:350,
    skill:{
      id:'cavalry',
      name:'騎兵決戦',
      cost:1,
      type:'decisive',
      text:'決戦スキル・自分の戦力を1.3倍する'
    },
    commands:{recruit:4,scheme:3,prepare:1}
  },

  lowja:{
    id:'lowja',
    name:'ハイエルフ・ロウジャ',
    role:'策士',
    race:'エルフ♀',
    rarity:2,
    power:800,
    charisma:350,
    intel:450,
    skill:{
      id:'guerrilla',
      name:'ゲリラ戦術',
      cost:2,
      type:'normal',
      text:'相手の戦力を知略の2.0倍減少'
    },
    commands:{recruit:1,scheme:5,prepare:2}
  },

  bonret:{
    id:'bonret',
    name:'天才詩人・ボンレット',
    role:'扇動者',
    race:'民間人♂',
    rarity:2,
    power:780,
    charisma:420,
    intel:380,
    skill:{
      id:'star',
      name:'主役抜擢',
      cost:2,
      type:'normal',
      text:'両ユニットのカリスマ合計値の1.2倍戦力増加'
    },
    commands:{recruit:3,scheme:3,prepare:2}
  },

  guren:{
    id:'guren',
    name:'炎の魔術師・紅蓮',
    role:'武勇',
    race:'魔術師♂',
    rarity:2,
    power:880,
    charisma:440,
    intel:550,
    skill:{
      id:'te_golem',
      name:'T・E・ゴーレム',
      cost:1,
      type:'normal',
      text:'このターン中、相手の策略倍率は0.5倍'
    },
    commands:{recruit:3,scheme:2,prepare:3}
  },

  crow:{
    id:'crow',
    name:'キャプテン・C・クロウ',
    role:'策士',
    race:'斥候♂',
    rarity:2,
    power:560,
    charisma:500,
    intel:480,
    skill:{
      id:'p_commander',
      name:'Pコマンダー',
      cost:2,
      type:'normal',
      text:'このターン、自分の両ユニットのステータス1.5倍'
    },
    commands:{recruit:2,scheme:3,prepare:3}
  },

  ggg:{
    id:'ggg',
    name:'GGGゴーレム',
    role:'英雄',
    race:'機械♀',
    rarity:2,
    power:1500,
    charisma:0,
    intel:500,
    skill:{
      id:'laser',
      name:'レーザービーム',
      cost:4,
      type:'normal',
      text:'相手戦力-1500、相手の準備1以上の全ユニットを0'
    },
    commands:{recruit:0,scheme:3,prepare:5}
  },

  jackeen:{
    id:'jackeen',
    name:'暗殺者（笑）・ジャキーン',
    role:'武勇',
    race:'斥候♂',
    rarity:2,
    power:960,
    charisma:400,
    intel:370,
    skill:{
      id:'recon',
      name:'威力偵察',
      cost:2,
      type:'normal',
      text:'相手の現在戦力を公開し、武力1.0倍分減少'
    },
    commands:{recruit:3,scheme:2,prepare:3}
  }
};
