// Character data for the free NPC battle demo.
const CHARS = {
  tsukune:{id:'tsukune',name:'騎兵隊長・ツクネ',role:'英雄',race:'騎士♀',rarity:2,power:1020,charisma:400,intel:350,skill:{id:'cavalry',name:'騎兵決戦',cost:1,type:'decisive',multiplier:1.3,text:'決戦スキル・自分の戦力を1.3倍する'},commands:{recruit:4,scheme:3,prepare:1}},
  lowja:{id:'lowja',name:'ハイエルフ・ロウジャ',role:'策士',race:'エルフ♀',rarity:2,power:800,charisma:350,intel:450,skill:{id:'guerrilla',name:'ゲリラ戦術',cost:1,type:'normal',text:'相手の戦力を知略の1.5倍減少'},commands:{recruit:1,scheme:5,prepare:2}},
  bonret:{id:'bonret',name:'天才詩人・ボンレット',role:'扇動者',race:'民間人♂',rarity:2,power:780,charisma:420,intel:380,skill:{id:'star',name:'主役抜擢',cost:2,type:'normal',text:'両ユニットのカリスマ合計値の1.2倍戦力増加'},commands:{recruit:3,scheme:3,prepare:2}},
  guren:{id:'guren',name:'炎の魔術師・紅蓮',role:'武勇',race:'魔術師♂',rarity:2,power:880,charisma:440,intel:550,skill:{id:'te_golem',name:'T・E・ゴーレム',cost:1,type:'normal',text:'このターン中、相手の招集の戦力増加倍率が0.5倍になる。この効果は重複しない'},commands:{recruit:3,scheme:2,prepare:3}},
  crow:{id:'crow',name:'キャプテン・C・クロウ',role:'策士',race:'斥候♂',rarity:2,power:560,charisma:500,intel:480,skill:{id:'p_commander',name:'Pコマンダー',cost:2,type:'normal',text:'このターン、自分の両ユニットのステータス1.5倍'},commands:{recruit:3,scheme:3,prepare:2}},
  ggg:{id:'ggg',name:'GGGゴーレム',role:'英雄',race:'機械♀',rarity:2,power:1500,charisma:0,intel:500,skill:{id:'laser',name:'レーザービーム',cost:4,type:'normal',text:'相手戦力-2000、相手の準備1以上の全ユニットを0'},commands:{recruit:0,scheme:3,prepare:5}},
  jackeen:{id:'jackeen',name:'暗殺者（笑）・ジャキーン',role:'武勇',race:'斥候♂',rarity:2,power:960,charisma:400,intel:370,skill:{id:'recon',name:'威力偵察',cost:2,type:'normal',text:'相手の現在戦力を公開し、武力1.0倍分減少'},commands:{recruit:3,scheme:2,prepare:3}},
  zazan:{id:'zazan',name:'闇剣士・ザザン',role:'英雄',race:'魔族♂',rarity:2,power:800,charisma:450,intel:400,skill:{id:'magic_sword',name:'魔剣',cost:3,type:'decisive',multiplier:1.7,text:'決戦スキル・自分の戦力を1.7倍する'},commands:{recruit:3,scheme:2,prepare:3}},
  larin:{id:'larin',name:'縛術士・ラーリン',role:'策士',race:'エルフ♀',rarity:2,power:770,charisma:380,intel:480,skill:{id:'binding_rope',name:'縛り紐',cost:2,type:'normal',text:'相手のすべてのユニットのステータスを0.8倍にする'},commands:{recruit:3,scheme:3,prepare:2}},
  olympus:{id:'olympus',name:'戦術家・オリンポス',description:'ロイドのパーティの戦術を担当している苦労人。',role:'策士',race:'戦略家♂',rarity:3,power:820,charisma:450,intel:500,skill:{id:'tactics',name:'戦術',cost:1,type:'normal',text:'この実働の次の実働だけ、自分の戦力減少量と相手の戦力上昇量を0.5倍にする。この効果は重複しない'},trait:'説得：毎ターン戦力を200増加',traitId:'persuasion',commands:{recruit:3,scheme:3,prepare:2}},
  hero_lloyd:{id:'hero_lloyd',name:'勇者・ロイド',description:'過去の英雄の息子で、今回魔王討伐隊（パーティー）を率いる事となった。',role:'英雄',race:'戦士♂',rarity:3,power:1000,charisma:450,intel:470,skill:{id:'holy_sword',name:'聖剣',cost:2,type:'normal',text:'戦力を1000増加'},trait:'主人公補正：★3以下のユニットと組む場合、武力+100、カリスマ・知略+50',traitId:'protagonist',commands:{recruit:3,scheme:2,prepare:3}},
  eiji:{id:'eiji',name:'槍使い・エイジ',description:'異世界からやってきた。はじめは勇者の座を奪うためロイドに絡んでいたが、この世界のために戦う決意をした。',role:'扇動者',race:'戦士♂',rarity:3,power:1060,charisma:350,intel:430,skill:{id:'peerless',name:'無双',cost:1,type:'decisive',multiplier:1.2,text:'決戦スキル・戦力を1.2倍にする'},trait:'異世界知識：招集を使う毎に自身のカリスマを1.1倍',traitId:'otherworld_knowledge',commands:{recruit:5,scheme:2,prepare:1}},
  solenarif:{id:'solenarif',name:'戦士・ソレナリフ',description:'師匠として勇者のパーティに参加した胡散臭いおっさん。',role:'英雄',race:'戦士♂',rarity:3,power:1100,charisma:430,intel:490,skill:{id:'insider',name:'事情通',cost:1,type:'normal',text:'相手の現在の戦力がわかる'},trait:'見切り：最初の戦略フェイズ開始時、全てのコマンドをデッキに戻して新しく8枚引くことを選べる',traitId:'foresight',evolutionGroup:'solenarif',note:'※真価可能ユニット',commands:{recruit:2,scheme:2,prepare:4}},
  solenarif_spy:{id:'solenarif_spy',name:'二重スパイ・ソレナリフ',formationName:'真価ソレナリフ',description:'魔王軍に裏切り勇者を窮地に追い込むが実は国王の命を受けた二重スパイ',role:'英雄',race:'戦略家♂',rarity:3,power:1100,charisma:430,intel:490,skill:{id:'spy',name:'スパイ',cost:2,type:'normal',text:'準備が1以上あるランダムな相手ユニット1体の準備を0にする。相手の現在の戦力がわかる'},trait:'見切り：最初の戦略フェイズ開始時、全てのコマンドをデッキに戻して新しく8枚引くことを選べる',traitId:'foresight',evolutionGroup:'solenarif',commands:{recruit:2,scheme:2,prepare:4}},
  arle:{id:'arle',name:'マジシャン・アーレ',description:'手品を得意とする少女\n魔力を使わないため人々を意外と驚かせられる。',role:'扇動者',race:'民間人♀',rarity:2,power:480,charisma:380,intel:450,skill:{id:'mulligan',name:'マリガン',cost:1,type:'normal',text:'手札をデッキに戻して新たに4枚引く。相手より戦力が低い場合、自分の他ユニットの準備を1増加する（この増加では特殊技能は発動しない）'},commands:{recruit:4,scheme:2,prepare:2}},
  gasshaan:{id:'gasshaan',name:'合体変形・ガッシャーン',description:'ドワーフの少女に作られたゴーレム。少女は合体メカが好きで自分で作ってしまった。中にはもちろんドワーフの少女が入っている。同志募集中',role:'扇動者',race:'機械♀',rarity:2,power:1100,charisma:400,intel:250,skill:{id:'reassembly',name:'分解、再合体',cost:3,type:'normal',text:'1回だけ戦力が0以下になった時、戦力100になる。次のターンの実働開始時に戦力を1000増加し、その次のターンの実働開始時に500増加する'},commands:{recruit:3,scheme:1,prepare:4}},
  donbura:{id:'donbura',name:'溺れる者・ドンブラー',description:'海モグラ族の青年。亀に乗って竜宮城へ行ったことがあるらしい。\n泳ぐのが好きだが、周りから溺れているとよく間違えられる。',role:'武勇',race:'魔族♂',rarity:2,power:800,charisma:400,intel:400,skill:{id:'discovery',name:'発見',cost:1,type:'normal',text:'相手の戦力と相手のキャラクターが見えるようになる'},commands:{recruit:4,scheme:3,prepare:1}},
  anmi:{id:'anmi',name:'リッチ・アンミ',description:'死者の王を自称する不死者。魔王とは敵対関係にあるが、それはそれとして勇者とも敵対している。ゾンビの兵団を用いた戦略を取ってくる。',role:'策士',race:'戦略家♀',rarity:2,power:700,charisma:350,intel:400,skill:{id:'infected_body',name:'感染体',cost:1,type:'normal',text:'このターン中、相手が招集を使用した時、相手の戦力を知略の1.0倍減少させる'},commands:{recruit:2,scheme:4,prepare:2}},
  vanilla:{id:'vanilla',name:'闘拳士・バニラ',role:'武勇',race:'民間人♂',rarity:1,power:800,charisma:400,intel:400,trait:'編成時に2体並べても良い',skill:{id:'vanilla_fist',name:'バニラ神拳',cost:2,type:'normal',text:'戦力を800増加させる'},commands:{recruit:3,scheme:3,prepare:2}},
  vanilla_clone:{id:'vanilla_clone',name:'闘拳士・バニラ',role:'武勇',race:'民間人♂',rarity:1,power:800,charisma:400,intel:400,trait:'編成時に2体並べても良い',selectable:false,skill:{id:'vanilla_fist',name:'バニラ神拳',cost:2,type:'normal',text:'戦力を800増加させる'},commands:{recruit:3,scheme:3,prepare:2}}
};
