// ==========================================
// NPCデッキデータ
// units: 使用する2体
// turns: 各ターン4回の行動
// recruit=招集 / scheme=策略 / prepare=準備
// ==========================================
const NPCS = {
  vanilla_twins:{
    name:'バニラ×2',
    style:'完全ランダム型',
    units:['vanilla','vanilla_clone'],
    randomActions:true
  },

  crow_bonret:{
    name:'クロウ＋ボンレット',
    style:'後半爆発型',
    units:['crow','bonret'],
    turns:[
      [
        ['bonret','recruit'],
        ['bonret','recruit'],
        ['bonret','recruit'],
        ['crow','scheme']
      ],
      [
        ['crow','prepare'],
        ['crow','scheme'],
        ['crow','scheme'],
        ['bonret','prepare']
      ],
      [
        ['crow','prepare'],
        ['bonret','prepare'],
        ['crow','recruit'],
        ['crow','recruit']
      ]
    ]
  },

  guren_lowja:{
    name:'紅蓮＋ロウジャ',
    style:'妨害型',
    units:['guren','lowja'],
    turns:[
      [
        ['guren','prepare'],
        ['lowja','scheme'],
        ['guren','recruit'],
        ['lowja','prepare']
      ],
      [
        ['lowja','prepare'],
        ['guren','prepare'],
        ['guren','recruit'],
        ['lowja','scheme']
      ],
      [
        ['guren','prepare'],
        ['guren','scheme'],
        ['guren','scheme'],
        ['lowja','scheme']
      ]
    ]
  },

  ggg_lowja:{
    name:'GGG＋ロウジャ',
    style:'準備破壊型',
    units:['ggg','lowja'],
    turns:[
      [
        ['ggg','prepare'],
        ['lowja','prepare'],
        ['ggg','prepare'],
        ['ggg','prepare']
      ],
      [
        ['ggg','scheme'],
        ['ggg','scheme'],
        ['ggg','scheme'],
        ['lowja','scheme']
      ],
      [
        ['lowja','scheme'],
        ['lowja','scheme'],
        ['ggg','prepare'],
        ['lowja','prepare']
      ]
    ]
  },

  tsukune_jackeen:{
    name:'ツクネ＋ジャキーン',
    style:'決戦型',
    units:['tsukune','jackeen'],
    turns:[
      [
        ['tsukune','recruit'],
        ['tsukune','recruit'],
        ['tsukune','recruit'],
        ['tsukune','recruit']
      ],
      [
        ['tsukune','prepare'],
        ['tsukune','recruit'],
        ['tsukune','recruit'],
        ['tsukune','recruit']
      ],
      [
        ['jackeen','prepare'],
        ['jackeen','prepare'],
        ['jackeen','scheme'],
        ['tsukune','scheme']
      ]
    ]
  },

  crow_jackeen:{
    name:'クロウ＋ジャキーン',
    style:'強化偵察型',
    units:['crow','jackeen'],
    turns:[
      [
        ['crow','scheme'],
        ['crow','scheme'],
        ['crow','scheme'],
        ['jackeen','prepare']
      ],
      [
        ['crow','prepare'],
        ['jackeen','recruit'],
        ['jackeen','recruit'],
        ['jackeen','recruit']
      ],
      [
        ['crow','prepare'],
        ['jackeen','prepare'],
        ['crow','recruit'],
        ['crow','recruit']
      ]
    ]
  },


  larin_jackeen:{
    name:'ラーリン＋ジャキーン',
    style:'能力減少型',
    units:['larin','jackeen'],
    turns:[
      [
        ['larin','prepare'],
        ['larin','prepare'],
        ['larin','recruit'],
        ['jackeen','recruit']
      ],
      [
        ['larin','scheme'],
        ['jackeen','prepare'],
        ['jackeen','prepare'],
        ['larin','recruit']
      ],
      [
        ['larin','scheme'],
        ['larin','recruit'],
        ['jackeen','recruit'],
        ['jackeen','recruit']
      ]
    ]
  },

  zazan_vanilla:{
    name:'ザザン＋バニラ',
    style:'重装決戦型',
    units:['vanilla','zazan'],
    turns:[
      [
        ['vanilla','recruit'],
        ['vanilla','recruit'],
        ['vanilla','recruit'],
        ['zazan','scheme']
      ],
      [
        ['vanilla','prepare'],
        ['vanilla','prepare'],
        ['zazan','recruit'],
        ['zazan','recruit']
      ],
      [
        ['zazan','recruit'],
        ['zazan','prepare'],
        ['zazan','prepare'],
        ['zazan','prepare']
      ]
    ]
  },

  ggg_guren:{
    name:'GGG＋紅蓮',
    style:'レーザー妨害型',
    units:['ggg','guren'],
    turns:[
      [
        ['guren','prepare'],
        ['ggg','scheme'],
        ['ggg','scheme'],
        ['ggg','scheme']
      ],
      [
        ['guren','prepare'],
        ['ggg','prepare'],
        ['ggg','prepare'],
        ['ggg','prepare']
      ],
      [
        ['ggg','prepare'],
        ['guren','prepare'],
        ['guren','scheme'],
        ['guren','scheme']
      ]
    ]
  }
};
