// Fixed NPC action tables. Each turn contains four [unit, command] entries.
const NPCS = {
  guren_lowja:{name:'紅蓮＋ロウジャ',style:'妨害型',units:['guren','lowja'],turns:[
    [['guren','prepare'],['lowja','scheme'],['guren','recruit'],['lowja','prepare']],
    [['lowja','prepare'],['guren','prepare'],['guren','recruit'],['lowja','scheme']],
    [['guren','prepare'],['guren','scheme'],['guren','scheme'],['lowja','scheme']]
  ]},
  crow_bonret:{name:'クロウ＋ボンレット',style:'後半爆発型',units:['crow','bonret'],turns:[
    [['bonret','recruit'],['bonret','recruit'],['bonret','recruit'],['crow','scheme']],
    [['crow','prepare'],['crow','scheme'],['bonret','recruit'],['bonret','prepare']],
    [['crow','prepare'],['bonret','prepare'],['bonret','recruit'],['bonret','recruit']]
  ]},
  tsukune_jackeen:{name:'ツクネ＋ジャキーン',style:'決戦型',units:['tsukune','jackeen'],turns:[
    [['tsukune','recruit'],['tsukune','recruit'],['tsukune','recruit'],['tsukune','recruit']],
    [['tsukune','prepare'],['jackeen','recruit'],['jackeen','recruit'],['jackeen','recruit']],
    [['jackeen','prepare'],['jackeen','prepare'],['tsukune','scheme'],['jackeen','scheme']]
  ]},
  crow_jackeen:{name:'クロウ＋ジャキーン',style:'強化偵察型',units:['crow','jackeen'],turns:[
    [['crow','scheme'],['crow','scheme'],['jackeen','prepare'],['crow','prepare']],
    [['crow','prepare'],['jackeen','prepare'],['crow','recruit'],['crow','recruit']],
    [['crow','recruit'],['jackeen','recruit'],['jackeen','recruit'],['jackeen','recruit']]
  ]},
  ggg_guren:{name:'GGG＋紅蓮',style:'レーザー妨害型',units:['ggg','guren'],turns:[
    [['guren','prepare'],['ggg','prepare'],['ggg','prepare'],['ggg','prepare']],
    [['ggg','prepare'],['guren','prepare'],['guren','scheme'],['guren','scheme']],
    [['guren','prepare'],['ggg','scheme'],['ggg','scheme'],['ggg','scheme']]
  ]},
  larin_jackeen:{name:'ラーリン＋ジャキーン',style:'能力減少型',units:['larin','jackeen'],turns:[
    [['larin','prepare'],['larin','prepare'],['larin','recruit'],['jackeen','recruit']],
    [['larin','scheme'],['jackeen','prepare'],['jackeen','prepare'],['larin','recruit']],
    [['larin','scheme'],['larin','recruit'],['jackeen','recruit'],['jackeen','recruit']]
  ]},
  ggg_lowja:{name:'GGG＋ロウジャ',style:'準備破壊型',units:['ggg','lowja'],turns:[
    [['ggg','prepare'],['ggg','prepare'],['ggg','prepare'],['ggg','prepare']],
    [['ggg','scheme'],['ggg','scheme'],['lowja','scheme'],['lowja','scheme']],
    [['lowja','scheme'],['lowja','prepare'],['lowja','prepare'],['ggg','scheme']]
  ]},
  zazan_vanilla:{name:'ザザン＋バニラ',style:'重装決戦型',units:['vanilla','zazan'],turns:[
    [['vanilla','recruit'],['vanilla','recruit'],['vanilla','recruit'],['zazan','scheme']],
    [['vanilla','prepare'],['vanilla','prepare'],['zazan','recruit'],['zazan','recruit']],
    [['zazan','recruit'],['zazan','prepare'],['zazan','prepare'],['zazan','prepare']]
  ]},
  guren_larin:{name:'紅蓮＋ラーリン',style:'複合妨害型',units:['guren','larin'],turns:[
    [['guren','prepare'],['larin','recruit'],['larin','recruit'],['larin','recruit']],
    [['guren','prepare'],['larin','prepare'],['larin','prepare'],['guren','scheme']],
    [['guren','scheme'],['guren','prepare'],['guren','recruit'],['guren','recruit']]
  ]},
  crow_lowja:{name:'クロウ＋ロウジャ',style:'策略強化型',units:['crow','lowja'],turns:[
    [['crow','recruit'],['crow','recruit'],['crow','recruit'],['crow','prepare']],
    [['crow','prepare'],['lowja','prepare'],['lowja','prepare'],['lowja','scheme']],
    [['lowja','recruit'],['lowja','scheme'],['lowja','scheme'],['lowja','scheme']]
  ]},
  bonret_zazan:{name:'ボンレット＋ザザン',style:'決戦支援型',units:['bonret','zazan'],turns:[
    [['zazan','prepare'],['zazan','prepare'],['zazan','prepare'],['zazan','scheme']],
    [['bonret','recruit'],['bonret','recruit'],['bonret','prepare'],['bonret','prepare']],
    [['zazan','recruit'],['zazan','recruit'],['bonret','scheme'],['bonret','scheme']]
  ]},
  lowja_jackeen:{name:'ロウジャ＋ジャキーン',style:'連続策略型',units:['lowja','jackeen'],turns:[
    [['jackeen','prepare'],['jackeen','prepare'],['lowja','prepare'],['lowja','scheme']],
    [['lowja','prepare'],['lowja','scheme'],['lowja','scheme'],['lowja','scheme']],
    [['lowja','scheme'],['jackeen','recruit'],['jackeen','recruit'],['jackeen','recruit']]
  ]},
  vanilla_twins:{name:'バニラ×2',style:'完全ランダム型',units:['vanilla','vanilla_clone'],randomActions:true}
};
